TextField and PageController updated
lukepighetti/pocketbase_flutter_app pull request #3
Opened 2022-09-17 00:49 UTC by Azzeccagarbugli

So basically, as you suggested during the wonderful [stream](https://www.twitch.tv/videos/1592863677), I fixed the following:

- `Viewport fraction` of the `PageController` 
- Improved `TextField` from my previous submission
- `AnnotedRegion` for the status bar brightness
- Clear `TextField` button just when the `TextField` itself is not empty

Enjoy 🎉

2022-09-17 20:10 UTC, lukepighetti commented
Hey! Can you post up a screenshot to go with your PR? Thanks

2022-09-17 20:20 UTC, Azzeccagarbugli commented
> Hey! Can you post up a screenshot to go with your PR? Thanks

Sure ✅

| Full screen  | Keyboard |
| ------------- | ------------- |
| ![Simulator Screen Shot - iPhone 14 Pro - 2022-09-17 at 22 17 47](https://user-images.githubusercontent.com/16477661/190875076-a96d4494-63e3-4f25-972f-3baad9a163b7.png) | ![Simulator Screen Shot - iPhone 14 Pro - 2022-09-17 at 22 18 04](https://user-images.githubusercontent.com/16477661/190875075-31feb0a9-189b-4b11-8c4c-d4dbdd685eed.png) |

2022-09-17 20:25 UTC, lukepighetti commented
Let's

- revert the back button style, 
- revert the text field text style, 
- re-center the text field,
- change the clear button to a basic material [clear](https://api.flutter.dev/flutter/material/Icons/clear-constant.html) icon 
- and make sure the text is centered

2022-09-17 20:43 UTC, Azzeccagarbugli commented
> * change the clear button to a basic material [clear](https://api.flutter.dev/flutter/material/Icons/clear-constant.html) icon

In this way, both the icons of the `go-back` action and the `clear-text` one will have the same icon though

2022-09-17 21:19 UTC, lukepighetti commented
We can leave out the clear button for now then, that should make it a lot easier

2022-09-17 21:22 UTC, Azzeccagarbugli commented
> We can leave out the clear button for now then, that should make it a lot easier

Do you mean leaving it out of the container that holds the `TextField` or completely removing it from the UI?

2022-09-17 21:47 UTC, lukepighetti commented
> > We can leave out the clear button for now then, that should make it a lot easier
> 
> Do you mean leaving it out of the container that holds the `TextField` or completely removing it from the UI?

If we can't keep everything nicely centered, let's remove the clear button feature completely

2022-09-17 21:59 UTC, Azzeccagarbugli commented
The last [commit](https://github.com/lukepighetti/pocketbase_flutter_app/pull/3/commits/2a3cb83300d78b3641600ad5f0a5bed0844953fb) should be fine now. Waiting for your feedback!

2022-09-17 23:51 UTC, lukepighetti requested changes
Couple more changes requested, thanks!

2022-09-17 23:51 UTC, lukepighetti commented on pb_app/lib/submission_form.dart
> +                  icon: const Icon(Icons.close_rounded),
```suggestion
                  icon: const Icon(Icons.close),
```

2022-09-17 23:51 UTC, lukepighetti commented on pb_app/lib/submission_form.dart
> +                          cursorColor: Colors.black26,
```suggestion
```

2022-09-17 23:51 UTC, lukepighetti commented on pb_app/lib/submission_form.dart
> +                          cursorColor: Colors.black26,
Let's not override the theme cursor color locally :)

2022-09-17 23:51 UTC, lukepighetti commented on pb_app/lib/submission_form.dart
> +                    icon: Icon(Icons.close_rounded),
```suggestion
                    icon: Icon(Icons.close),
```

2022-09-17 23:51 UTC, lukepighetti commented on pb_app/lib/submission_form.dart
> +              : const _Card('Lock Screen'),
```suggestion
         body: PageView(
           children: const [
            _Card('Home Screen'),
            _Card('Lock Screen'),
          ],
```

We won't see a performance benefit using PageView.builder here, so the added complexity is not worth it

2022-09-17 23:51 UTC, lukepighetti commented on pb_app/lib/submission_form.dart
> +          // debugPrint('I have been clicked even if the ripple isn\'t showing');
```suggestion
```

2022-09-17 23:55 UTC, lukepighetti commented
Also, let's get this up to date with main branch so we can get ci checks on it

2022-09-18 00:14 UTC, Azzeccagarbugli commented
Thank a lot for the code review, hopefully, the process of the next PR is going to be more seamless.

Would be pretty helpful to have a project board or a bunch of issues so that we could work **specifically** on some features.

2022-09-18 01:01 UTC, lukepighetti commented
Yes! Please bare with me as I make it easier for folks to contribute.

Had one more change request (my mistake!) And the files do need to get reformatted.

Thank you

2022-09-18 01:17 UTC, lukepighetti commented
You can also merge in `main` and it should auto format and commit for you

2022-09-18 10:58 UTC, Azzeccagarbugli commented
> Yes! Please bare with me as I make it easier for folks to contribute.
> 
> Had one more change request (my mistake!) And the files do need to get reformatted.
> 
> Thank you

The code review is marked as resolved so I don't understand which other request I'm missing 😅

2022-09-18 11:20 UTC, lukepighetti commented
Woops! I must have forgotten to submit the review on my office computer. The page controller needs to be hooked up again.

2022-09-18 11:29 UTC, Azzeccagarbugli commented
> Woops! I must have forgotten to submit the review on my office computer. The page controller needs to be hooked up again.

Done it ✅

2022-09-18 18:33 UTC, lukepighetti requested changes
As they say, 'first one through the wall gets bloody.'

2022-09-18 18:33 UTC, lukepighetti commented on pb_app/lib/submission_form.dart
> +          // TODO: InkWell not working properly into stack (https://github.com/flutter/flutter/issues/104519)
This issue was resolved in https://github.com/lukepighetti/pocketbase_flutter_app/commit/e374c182affd4a2debd5b4b0a1647de493d78685 so the comment should be removed

2022-09-18 18:33 UTC, lukepighetti commented on pb_app/lib/submission_form.dart
> -            ),
can we revert these changes? they are having no effect

2022-09-18 18:33 UTC, lukepighetti commented on pb_app/lib/submission_form.dart
> +            ),
can we revert these changes? they are having no effect

2022-09-18 19:51 UTC, merged

2022-09-18 19:51 UTC, lukepighetti commented
Thank you!